EXEC dbo.repAntiguedadSaldos @sEmpresa = 'TUN',       -- char(5)
                             @dInicio = '2018-11-01', -- date
                             @dFin = '2018-11-30',    -- date
                             @sCliente = '79366     ',
                             @bGenerar = 1;        -- bit
EXEC dbo.repAntiguedadSaldos @sEmpresa = 'TUN',       -- char(5)
                             @dInicio = '2018-11-01', -- date
                             @dFin = '2018-11-30',    -- date
                             @sCliente = NULL,        -- varchar(10)
                             @bGenerar = 0;        -- bit
